// File generated by FlutterFire CLI, then modified to read values from `.env`.
// DO NOT commit real Firebase API keys here. Keep them in `.env` (git-ignored).
// If you regenerate this file with `flutterfire configure`, re-apply the
// EnvConfig changes or move the generated values into your `.env` file.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:ali_app/services/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: EnvConfig.get('FIREBASE_API_KEY_WEB'),
    appId: EnvConfig.get('FIREBASE_APP_ID_WEB'),
    messagingSenderId: EnvConfig.get('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: EnvConfig.get('FIREBASE_PROJECT_ID'),
    authDomain: EnvConfig.get('FIREBASE_AUTH_DOMAIN'),
    storageBucket: EnvConfig.get('FIREBASE_STORAGE_BUCKET'),
    measurementId: EnvConfig.get('FIREBASE_MEASUREMENT_ID_WEB'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: EnvConfig.get('FIREBASE_API_KEY_ANDROID'),
    appId: EnvConfig.get('FIREBASE_APP_ID_ANDROID'),
    messagingSenderId: EnvConfig.get('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: EnvConfig.get('FIREBASE_PROJECT_ID'),
    storageBucket: EnvConfig.get('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: EnvConfig.get('FIREBASE_API_KEY_IOS'),
    appId: EnvConfig.get('FIREBASE_APP_ID_IOS'),
    messagingSenderId: EnvConfig.get('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: EnvConfig.get('FIREBASE_PROJECT_ID'),
    storageBucket: EnvConfig.get('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: EnvConfig.get('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: EnvConfig.get('FIREBASE_API_KEY_IOS'),
    appId: EnvConfig.get('FIREBASE_APP_ID_IOS'),
    messagingSenderId: EnvConfig.get('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: EnvConfig.get('FIREBASE_PROJECT_ID'),
    storageBucket: EnvConfig.get('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: EnvConfig.get('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: EnvConfig.get('FIREBASE_API_KEY_WEB'),
    appId: EnvConfig.get('FIREBASE_APP_ID_WINDOWS'),
    messagingSenderId: EnvConfig.get('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: EnvConfig.get('FIREBASE_PROJECT_ID'),
    authDomain: EnvConfig.get('FIREBASE_AUTH_DOMAIN'),
    storageBucket: EnvConfig.get('FIREBASE_STORAGE_BUCKET'),
    measurementId: EnvConfig.get('FIREBASE_MEASUREMENT_ID_WINDOWS'),
  );
}
